name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.RITIKRAJ }}" | docker login -u "ritik1001" --password-stdin
        docker image build -t ritik1001/flashapp:latest .
        docker push ritik1001/flashapp:latest
